language: php
php:
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

sudo: required

before_install:
  - mysql -e "create database IF NOT EXISTS hike_v3_01_test;" -u root
  - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'test'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;"
  - mysql -e "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" -u root


before_script:
  - chmod +x ./tests/travis/setup/before_script.sh
  - chmod +x ./tests/travis/setup/setup_apache.sh
  - chmod +x ./tests/travis/setup/setup_selenium_server.sh
  - ./tests/travis/setup/before_script.sh
  - ./tests/travis/setup/setup_apache.sh
  - ./tests/travis/setup/setup_selenium_server.sh

script:
  - ls -la
  - cd tests/codeception
  - ls -la
  - ../../vendor/bin/codecept run
##notifications:
##  email:
##    - dasscheman@hotmail.com
