language: php

php:
  - 5.4
  - 5.5
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

addons:
  hosts:
    - hike.devel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e "create database IF NOT EXISTS hikeapptest;" -u root
  - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'secret';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'test'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;"
  - mysql -e "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" -u root

install:
  - cp config/db.php.dist config/db.php
  - sed -i "s/$db = require(__DIR__ . '/db.php');/$db = require(__DIR__ . '/test_db.php');/" config/console.php
  - travis_retry composer self-update && composer --version
#  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer global require "fxp/composer-asset-plugin"
  - composer install
  - php yii migrate/up --migrationPath=@yii/rbac/migrations
  - php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations
  - travis_retry composer update --no-interaction
  # install php extensions
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping imagick and gmagick tests on HHVM"
    else
      pear config-set preferred_state beta
      printf "\n" | pecl install imagick
      # gmagick is not installed on travis currently
      #printf "\n" | pecl install gmagick
    fi
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/test.php

script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    vendor/bin/codecept run functional